services:
  meshmeshgo:
    image: ghcr.io/espmeshmesh/amd64-meshmeshgo-addon:latest
    container_name: meshmeshgo
    network_mode: host
    privileged: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - ./:/data:rw
    restart: unless-stopped
    